version: 2.1

jobs:
  release:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Semantic Release
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              npx semantic-release
            else
              echo "Skipping semantic-release for branch ${CIRCLE_BRANCH}"
            fi

workflows:
  version: 2
  main:
    jobs:
      - release:
          name: Semantic Release
          filters:
            branches:
              only:
                - main
